os: linux
dist: xenial
language: cpp
compiler: clang

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
  - sudo apt-get -qq update
  - sudo apt-get install -qq --yes --force-yes qt58-meta-minimal 
  - qmake --version
  - git clone https://github.com/grame-cncm/guidolib.git guidolib
  - make -C guidolib/build linux LINUXMIDI=no
  - sudo make -C guidolib/build/linux install
  - git clone https://github.com/grame-cncm/guidoar.git guidoar
  - make -C guidoar/build MIDIEXPORT=no
  - sudo make -C guidoar/build/linux install
  
 
branches:
  only:
  - dev
  - master

script: make -C build
