os: linux
dist: xenial
language: cpp
compiler: clang

before_install:
  - sudo apt-get -qq update
  - qmake --version
  - git clone https://github.com/grame-cncm/guidolib.git guidolib
  - make -C guidolib/build
  - sudo make -C guidolib/build/linux install
  - git clone https://github.com/grame-cncm/guidoar.git guidoar
  - make -C guidoar/build
  - sudo make -C guidoar/build/linux install
  
 
branches:
  only:
  - dev
  - master

script: make -C build
