os: linux
dist: trusty
sudo: required
language: cpp
compiler: clang

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
  - sudo apt-get update -qq
  - sudo apt-get install -y libmicrohttpd-dev libpulse-dev
  - sudo apt-get install qt58-meta-full
  - source /opt/qt58/bin/qt58-env.sh
  - qmake --version  
  - git clone --depth 1 --single-branch -b dev  https://github.com/grame-cncm/guidolib.git guidolib
  - make -C guidolib/build basic CMAKEOPT="-DMIDIEXPORT=no"
  - sudo make -C guidolib/build/guidodir install
  - git clone --depth 1 --single-branch -b dev https://github.com/grame-cncm/guidoar.git guidoar
  - make -C guidoar/build MIDIEXPORT=no
  - sudo make -C guidoar/build/linux install
 
branches:
  only:
  - dev
  - master

script: make -C build 

